// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZJfA_LyDTOWRKpb2bED1_ox1Oe4gzUE',
    appId: '1:161410344201:web:0923b36e6c34b7b90cdfd8',
    messagingSenderId: '161410344201',
    projectId: 'weather-monitor-70793',
    authDomain: 'weather-monitor-70793.firebaseapp.com',
    storageBucket: 'weather-monitor-70793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9zw4XdYiyWkgHWL26trOuuHi560lrAK4',
    appId: '1:161410344201:android:56b97fffa1681fb40cdfd8',
    messagingSenderId: '161410344201',
    projectId: 'weather-monitor-70793',
    storageBucket: 'weather-monitor-70793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhC-Qghlj8ej5j2MIagts3Bc5hoemqv50',
    appId: '1:161410344201:ios:776bba7b1ec3854d0cdfd8',
    messagingSenderId: '161410344201',
    projectId: 'weather-monitor-70793',
    storageBucket: 'weather-monitor-70793.appspot.com',
    iosClientId: '161410344201-11cd6g1gj3vhijjmiik7s6hdv0at74pe.apps.googleusercontent.com',
    iosBundleId: 'com.weathermonitor.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhC-Qghlj8ej5j2MIagts3Bc5hoemqv50',
    appId: '1:161410344201:ios:090fadaaf6d4e50e0cdfd8',
    messagingSenderId: '161410344201',
    projectId: 'weather-monitor-70793',
    storageBucket: 'weather-monitor-70793.appspot.com',
    iosClientId: '161410344201-0vomm63i3snrqm03ascc4bq6hndli0cg.apps.googleusercontent.com',
    iosBundleId: 'com.weathermonitor.weatherapp.RunnerTests',
  );
}
